modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="LGPL 2.1"

[[mods]] #mandatory
    modId="cobblefordays" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Cobble For Days" #mandatory
    authors="Lex" #optional
    description="A set of simple cobblestone generators. Mainly useful for servers that don't want multi-block cobblegens."